### ISSUE TITLE
[Bug] Navigation for RichEditToolbar is goes to a wrong page in Documentation(https://made-apps.github.io/MADE-Uno/articles/intro.html#uicontrolsrichedittoolbar) 

### ISSUE THREAD

**Issue by avikeid2007** [MADE-Apps/MADE-Uno#42]
### Describe the bug

Currently, In Documentation(https://made-apps.github.io/MADE-Uno/articles/intro.html) When clicking on Discover UI.Controls.RichEditToolbar button it navigate to /articles/features/ui-controls-filepicker.html page.

### What is the expected behavior?

Should navigate to /articles/features/ui-controls-richedittoolbar.html page.

**Comment by jamesmcroft** [comment]
This has now been merged and deployed to the docs 😄 

Thanks for supporting the project 🙌
